[theme]
primaryColor = "#6950f3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f2f2"
textColor = "#0d0d0d"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableStaticServing = true
